// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1cj6oHLQqI6ucVKBvVzbvqRo7r65_sKw',
    appId: '1:591120343721:web:7ab68c6083615891f8bfb8',
    messagingSenderId: '591120343721',
    projectId: 'whatshop-5a3f8',
    authDomain: 'whatshop-5a3f8.firebaseapp.com',
    storageBucket: 'whatshop-5a3f8.firebasestorage.app',
    measurementId: 'G-R0G8GXZ4ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp7QqR6WZb_PgJZqjsl2AQkZ5zLE_wqqA',
    appId: '1:591120343721:android:5168740960f23bb6f8bfb8',
    messagingSenderId: '591120343721',
    projectId: 'whatshop-5a3f8',
    storageBucket: 'whatshop-5a3f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHjlNmA8WOU5IkQZTMxJfXX3TUucjRfy4',
    appId: '1:591120343721:ios:22d37028358e6df8f8bfb8',
    messagingSenderId: '591120343721',
    projectId: 'whatshop-5a3f8',
    storageBucket: 'whatshop-5a3f8.firebasestorage.app',
    iosBundleId: 'com.whatshop.whatshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHjlNmA8WOU5IkQZTMxJfXX3TUucjRfy4',
    appId: '1:591120343721:ios:22d37028358e6df8f8bfb8',
    messagingSenderId: '591120343721',
    projectId: 'whatshop-5a3f8',
    storageBucket: 'whatshop-5a3f8.firebasestorage.app',
    iosBundleId: 'com.whatshop.whatshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1cj6oHLQqI6ucVKBvVzbvqRo7r65_sKw',
    appId: '1:591120343721:web:0e33f01c2a3be79ff8bfb8',
    messagingSenderId: '591120343721',
    projectId: 'whatshop-5a3f8',
    authDomain: 'whatshop-5a3f8.firebaseapp.com',
    storageBucket: 'whatshop-5a3f8.firebasestorage.app',
    measurementId: 'G-TDP796K4NF',
  );

}