// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgCcsWTyIdZZq407Mz3HVYYSqYlU6LFCU',
    appId: '1:213064130390:web:5de7e707e1e6fc138140f7',
    messagingSenderId: '213064130390',
    projectId: 'whatshop-b54b3',
    authDomain: 'whatshop-b54b3.firebaseapp.com',
    databaseURL: 'https://whatshop-b54b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whatshop-b54b3.firebasestorage.app',
    measurementId: 'G-TXLB72Z1Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT5DM2mntBd3Qv34EUdw0AAs2DmRlrFUw',
    appId: '1:213064130390:android:b999c6f3f7e1733e8140f7',
    messagingSenderId: '213064130390',
    projectId: 'whatshop-b54b3',
    databaseURL: 'https://whatshop-b54b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whatshop-b54b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCARdZ_HlAWljuHpVfUX8XDNX79bI3jX80',
    appId: '1:213064130390:ios:eeda28847a0a34358140f7',
    messagingSenderId: '213064130390',
    projectId: 'whatshop-b54b3',
    databaseURL: 'https://whatshop-b54b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whatshop-b54b3.firebasestorage.app',
    iosBundleId: 'com.whatshop.whatshop',
  );
}
